### ISSUE TITLE
Too many # at the end of my title line

### ISSUE THREAD

**Issue by MargauxSan** [ThinkRstat/littleboxes#3]
Hi there! 

I have a super small issue with the boxes... 
From: 
![image](https://cloud.githubusercontent.com/assets/22079331/21989565/b2c2ed72-dc0b-11e6-8dba-a3ef86b146a8.png)
I obtain: 
![image](https://cloud.githubusercontent.com/assets/22079331/21989600/d3d8eb74-dc0b-11e6-9743-3985ebb6a6d6.png)
One of my colleague has the same problem with one computer but not the other. 
Any ideas to solve it?
=]

**Comment by Bisaloo** [comment]
Yup, I noticed this issue as well since https://github.com/ThinkRstat/littleboxes/commit/b4b97bd8bfac871a20660b4219d92b34e047d405.

I am unsure what the purpose of this commit is.

Are you sure your colleague uses the latest github version of this addin? Ask them to run 
```r
devtools::install_github("ThinkRstat/littleboxes")
```
My guess is that they should now be able to reproduce your issue.

For the time being, you can probably go around this issue by using my fork, where I reverted the faulty commit. Run:
```r
devtools::install_github("Bisaloo/littleboxes")
```
Restart rstudio and it should now work.

**Comment by VincentGuyader** [comment]
the extra ### was a request from some users. The purpose was to use the collapse functionnality from Rstudio
see [https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections](url)

I will make a new branch without this.

thanks @Bisaloo for your review

**Comment by VincentGuyader** [comment]
devtools::install_github("ThinkRstat/littleboxes") # without ####
devtools::install_github("ThinkRstat/littleboxes",ref="collapse") # with ####
