### ISSUE TITLE
Feature Request: Add trailing ---- to enable RStudio section skipping feature

### ISSUE THREAD

**Issue by charliejhadley** [ThinkRstat/littleboxes#8]
As suggested by ma_salmon on Twitter here https://twitter.com/ma_salmon/status/928626214889312256

![image](https://user-images.githubusercontent.com/9363263/32611367-559c55c0-c55d-11e7-8084-c6e4887b049e.png)

**Comment by jonocarroll** [comment]
Just wondering since this came to my attention again -- is this resolved via https://github.com/ThinkR-open/littleboxes/issues/6? [Any 4 or more](https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections) of `-`,  `=`, or `#` at the end of a line works, so my suggestion was to pad with `#`. It's been in the master version since Jun last year. Or was this looking for something different? cc @maelle

**Comment by maelle** [comment]
I haven't used the addin a lot recently so can't remember sorry!

**Comment by VincentGuyader** [comment]
I think we can close this issue. 
now , by default, you can collapse the section.

```
##%######################################################%##
#                                                          #
####                       coucou                       ####
#                                                          #
##%######################################################%##


```
